"""initial_migration

Revision ID: 188fc65a4c02
Revises: None
Create Date: 2026-06-30 14:17:45.673347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.models


# revision identifiers, used by Alembic.
revision: str = '188fc65a4c02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('wallet_address', sa.String(length=255), nullable=True),
    sa.Column('email_domain', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='company_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_companies_name'),
    sa.UniqueConstraint('registration_number', name='uq_companies_registration_number'),
    sa.UniqueConstraint('wallet_address', name='uq_companies_wallet_address')
    )
    op.create_index('idx_companies_name', 'companies', ['name'], unique=False)
    op.create_index('idx_companies_registration_number', 'companies', ['registration_number'], unique=False)
    op.create_index('idx_companies_status', 'companies', ['status'], unique=False)
    op.create_index('idx_companies_wallet_address', 'companies', ['wallet_address'], unique=False)
    op.create_table('registries',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('accreditation', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_registries_name')
    )
    op.create_index('idx_registries_name', 'registries', ['name'], unique=False)
    op.create_index('idx_registries_status', 'registries', ['status'], unique=False)
    op.create_table('carbon_projects',
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('project_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=False),
    sa.Column('verification_standard', sa.String(length=100), nullable=False),
    sa.Column('methodology', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('developer', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['registry_id'], ['registries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code', name='uq_carbon_projects_project_code')
    )
    op.create_index('idx_carbon_projects_name', 'carbon_projects', ['name'], unique=False)
    op.create_index('idx_carbon_projects_project_code', 'carbon_projects', ['project_code'], unique=False)
    op.create_index('idx_carbon_projects_status', 'carbon_projects', ['status'], unique=False)
    op.create_table('users',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'COMPANY_ADMIN', 'TRADER', 'AUDITOR', 'VIEWER', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_values', app.models.models.JSONB(), nullable=True),
    sa.Column('new_values', app.models.models.JSONB(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_company_id', 'audit_logs', ['company_id'], unique=False)
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('credit_batches',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=False),
    sa.Column('total_credits', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('remaining_credits', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('issuance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PARTIALLY_USED', 'RETIRED', 'EXPIRED', name='batch_status_enum'), nullable=False),
    sa.Column('metadata_json', app.models.models.JSONB(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('remaining_credits <= total_credits', name='chk_credit_batches_remaining_credits_limit'),
    sa.CheckConstraint('remaining_credits >= 0', name='chk_credit_batches_remaining_credits_nonnegative'),
    sa.CheckConstraint('total_credits > 0', name='chk_credit_batches_total_credits_positive'),
    sa.CheckConstraint('vintage_year <= 2026', name='chk_credit_batches_vintage_year_limit'),
    sa.ForeignKeyConstraint(['project_id'], ['carbon_projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_number', name='uq_credit_batches_batch_number')
    )
    op.create_index('idx_credit_batches_batch_number', 'credit_batches', ['batch_number'], unique=False)
    op.create_index('idx_credit_batches_status', 'credit_batches', ['status'], unique=False)
    op.create_index('idx_credit_batches_vintage_year', 'credit_batches', ['vintage_year'], unique=False)
    op.create_table('project_documents',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('VERIFICATION_CERTIFICATE', 'MONITORING_REPORT', 'METHODOLOGY', 'ISSUANCE_CERTIFICATE', 'IMAGE', 'OTHER', name='document_type_enum'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['carbon_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('token_jti', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('reused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_jti', name='uq_refresh_tokens_token_jti')
    )
    op.create_index('idx_refresh_tokens_token_jti', 'refresh_tokens', ['token_jti'], unique=False)
    op.create_index('idx_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('ownerships',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('owned_credits', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('average_purchase_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('average_purchase_price >= 0', name='chk_ownerships_average_purchase_price_nonnegative'),
    sa.CheckConstraint('owned_credits > 0', name='chk_ownerships_owned_credits_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['credit_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ownerships_batch_company', 'ownerships', ['batch_id', 'company_id'], unique=False)
    op.create_table('marketplace_listings',
    sa.Column('ownership_id', sa.UUID(), nullable=False),
    sa.Column('seller_company_id', sa.UUID(), nullable=False),
    sa.Column('credits_for_sale', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price_per_credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('minimum_purchase', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'REJECTED', 'CANCELLED', 'COMPLETED', name='listing_status_enum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('credits_for_sale > 0', name='chk_listings_credits_for_sale_positive'),
    sa.CheckConstraint('minimum_purchase >= 1', name='chk_listings_minimum_purchase_limit'),
    sa.CheckConstraint('price_per_credit > 0', name='chk_listings_price_per_credit_positive'),
    sa.ForeignKeyConstraint(['ownership_id'], ['ownerships.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_marketplace_listings_status', 'marketplace_listings', ['status'], unique=False)
    op.create_table('retirements',
    sa.Column('ownership_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('credits_retired', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=False),
    sa.Column('blockchain_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('credits_retired > 0', name='chk_retirements_credits_retired_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ownership_id'], ['ownerships.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blockchain_tx_hash', name='uq_retirements_blockchain_tx_hash'),
    sa.UniqueConstraint('certificate_number', name='uq_retirements_certificate_number')
    )
    op.create_index('idx_retirements_blockchain_tx_hash', 'retirements', ['blockchain_tx_hash'], unique=False)
    op.create_index('idx_retirements_certificate_number', 'retirements', ['certificate_number'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_company_id', sa.UUID(), nullable=False),
    sa.Column('requested_credits', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price_per_credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED', name='purchase_order_status_enum'), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price_per_credit > 0', name='chk_orders_price_per_credit_positive'),
    sa.CheckConstraint('requested_credits > 0', name='chk_orders_requested_credits_positive'),
    sa.CheckConstraint('total_price > 0', name='chk_orders_total_price_positive'),
    sa.ForeignKeyConstraint(['buyer_company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_purchase_orders_status', 'purchase_orders', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('buyer_company_id', sa.UUID(), nullable=False),
    sa.Column('seller_company_id', sa.UUID(), nullable=False),
    sa.Column('ownership_id', sa.UUID(), nullable=False),
    sa.Column('credits_transferred', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price_per_credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('blockchain_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('credits_transferred > 0', name='chk_transactions_credits_transferred_positive'),
    sa.CheckConstraint('price_per_credit > 0', name='chk_transactions_price_per_credit_positive'),
    sa.CheckConstraint('total_price > 0', name='chk_transactions_total_price_positive'),
    sa.ForeignKeyConstraint(['buyer_company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ownership_id'], ['ownerships.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blockchain_tx_hash', name='uq_transactions_blockchain_tx_hash'),
    sa.UniqueConstraint('order_id', name='uq_transactions_order_id')
    )
    op.create_index('idx_transactions_blockchain_tx_hash', 'transactions', ['blockchain_tx_hash'], unique=False)
    op.create_index('idx_transactions_status', 'transactions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_status', table_name='transactions')
    op.drop_index('idx_transactions_blockchain_tx_hash', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('idx_purchase_orders_status', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index('idx_retirements_certificate_number', table_name='retirements')
    op.drop_index('idx_retirements_blockchain_tx_hash', table_name='retirements')
    op.drop_table('retirements')
    op.drop_index('idx_marketplace_listings_status', table_name='marketplace_listings')
    op.drop_table('marketplace_listings')
    op.drop_index('idx_ownerships_batch_company', table_name='ownerships')
    op.drop_table('ownerships')
    op.drop_index('idx_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_token_jti', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('project_documents')
    op.drop_index('idx_credit_batches_vintage_year', table_name='credit_batches')
    op.drop_index('idx_credit_batches_status', table_name='credit_batches')
    op.drop_index('idx_credit_batches_batch_number', table_name='credit_batches')
    op.drop_table('credit_batches')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_company_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_carbon_projects_status', table_name='carbon_projects')
    op.drop_index('idx_carbon_projects_project_code', table_name='carbon_projects')
    op.drop_index('idx_carbon_projects_name', table_name='carbon_projects')
    op.drop_table('carbon_projects')
    op.drop_index('idx_registries_status', table_name='registries')
    op.drop_index('idx_registries_name', table_name='registries')
    op.drop_table('registries')
    op.drop_index('idx_companies_wallet_address', table_name='companies')
    op.drop_index('idx_companies_status', table_name='companies')
    op.drop_index('idx_companies_registration_number', table_name='companies')
    op.drop_index('idx_companies_name', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
